updated WP content
SwissOpenEM/swissopenem.github.io pull request #4
Opened 2024-11-19 12:38 UTC by sofyalaski

I updated the description of WP 1 and 3 a little and added some links. Please tell me what you think or also change. 

### WP1 
task 1 description updated:
* added bullet points, because the text wasn't actually a text I think? 
* added some changes about oscem ( not a draft anymore, added link)
* Commented out "Conversion tools under development for major instrument manufacturers and formats" does that only include WP3 or something else? You can put it back, but it needs clarification which formats/manufactures meant. 

### WP3
* added more info and links to task 1
* task2 now has a little more details. @despadam you are very welcome to add other sources.

2024-11-19 13:07 UTC, sbliven requested changes
Doesn't this need to update the site data too to mark 3.2 as 'Done'?

2024-11-19 13:07 UTC, sbliven commented on deliverable-wp1.md
> +Workshop 22-23 Feb 2024 with participants from facilities, software developers and repositories curators.
Dropped a bullet symbol here

2024-11-19 13:07 UTC, sbliven commented on deliverable-wp1.md
> +<!-- Conversion tools under development for major instrument manufacturers and formats -->
Why commented? Let's rather day 'tools available for ... formats (Thermo Fisher EPU and SerialEM)'

2024-11-19 13:27 UTC, sofyalaski commented on deliverable-wp1.md
> +Workshop 22-23 Feb 2024 with participants from facilities, software developers and repositories curators.
oh thanks

2024-11-19 13:38 UTC, sofyalaski commented on deliverable-wp1.md
> +<!-- Conversion tools under development for major instrument manufacturers and formats -->
yes, the clarification was missing for me. I added it back.

2024-11-19 13:47 UTC, sofyalaski commented
@sbliven, sorry,  I am a bit lost. Did you mean repository integration task2? Because I think I would then shift it to "in progress". Me and Despina talked today and thought maybe it's too early to say we are not going to implement any automatic deposition for material sciences. The way it's written now is probably not the best and I will add a sentence that we are still planning to implement something. In the next milestone, both Me and Despina will try to find out more about these and other databases. 

Anyway, I first thought your comment was about WP1 task 3, that the web-page is now working. So I added a bit more complete sentences. If that's not correct, I can revert.

2024-11-19 14:40 UTC, despadam requested changes

2024-11-19 14:45 UTC, sofyalaski commented
I also wanted to change the figure that is cited in WP2. @sbliven, do you have it somewhere in a better resolution?

2024-11-19 15:11 UTC, ytittes approved these changes

2024-11-19 15:40 UTC, despadam approved these changes

2024-11-20 10:20 UTC, sbliven commented
@sofyalaski 
> Did you mean repository integration task2? Because I think I would then shift it to "in progress". Me and Despina talked today and thought maybe it's too early to say we are not going to implement any automatic deposition for material sciences.

👍 'In progress' is fine

> I also wanted to change the figure that is cited in WP2. @sbliven, do you have it somewhere in a better resolution?

I can't find the source. Best resolution is 1317 × 761: [230711 scicat overview.png](https://drive.google.com/open?id=12lfy8BKvImjd4_d6hdvQKr7OPoyNHFJw&usp=drive_fs)

2024-11-20 15:41 UTC, merged